### ISSUE TITLE
nerd-dictation doesn't end when icon is pressed

### ISSUE THREAD

**Issue by cmt29** [papoteur-mga/elograf#1]
Hi, I've tried installing your nice gui for nerd-dictation. Not sure I've done it right though! Anyway, everything seems fine until I try to click the icon to turn off dictation - but whilst the icon changes, nerd-dictation is still running and dictation is still active. Is there something I might be doing wrong?

**Comment by hv15** [comment]
can confirm, nerd-dictation starts fine but the process doesn't end either by clicking on the icon *or* by exiting elograf.

**Comment by papoteur-mga** [comment]
Hello,
Thanks for the feedback.
Indeed, the 2 last commits aren't OK.
Please use 0.3.0 release for the moment.

**Comment by cmt29** [comment]
Thanks but I think I am already using 0.3.0.

**Comment by papoteur-mga** [comment]
Hello,
The commit https://github.com/papoteur-mga/elograf/commit/87cb8c6d823c6e43755f8e3bb01df1ca26c17b79 should restore a stop command.
How did you determine that you run 0.3.0?

**Comment by cmt29** [comment]
The latest entry in the changelog in my downloaded copy says 0.3.0.

**Comment by papoteur-mga** [comment]
Release 0.3.1 should fix that.
