### ISSUE TITLE
Continue Development?

### ISSUE THREAD

**Issue by qalisto** [papoteur-mga/elograf#10]
Thank you Papoteur for this promising 'enabling tool'.

Might you have time to make further improvements to the UI and 'overall' functionality?

We believe that nerd-dictation is going to grow and your tool will become a "must-have".

We hope you can find time to finish to higher level.

Regards,  Q

**Comment by papoteur-mga** [comment]
Hello,
I consider that it is stable enough.
If you encounter problem or have suggestion on improvement, say it here or through a specific issue.

**Comment by papoteur-mga** [comment]
No  more comments, thus closing.
