### ISSUE TITLE
Default icons are not loaded

### ISSUE THREAD

**Issue by mfat** [papoteur-mga/elograf#11]
Default icons that come with Elograf are not loaded. Instead I see the attached icons.
![Screenshot_20230906_232601](https://github.com/papoteur-mga/elograf/assets/423263/ffa1095b-ad05-4736-b51b-98a59757d36c)
![Screenshot_20230906_232547](https://github.com/papoteur-mga/elograf/assets/423263/960dcf96-715d-48b9-9fce-a9dc5208c8d2)
I'm using the latest KDE on Fedora.

**Comment by papoteur-mga** [comment]
Hello,
The icons are loaded at preference from theme.
The first one should be the icon `audio-input-microphone`, as the second one should be `microphone-sensitivity-muted`
Which icon theme are you using?

**Comment by papoteur-mga** [comment]
No answer, thus closing.
