### ISSUE TITLE
Italian Translation Missing

### ISSUE THREAD

**Issue by albanobattistella** [papoteur-mga/elograf#18]
Hi,

Italian translation is missing on the interface.
Could you please check it?
Thanks!
A.

**Comment by papoteur-mga** [comment]
Hello,
Thanks for providing the translation.
From which installation the translation is missing ?
Translations are provided by a qm file which is computed when the setup is executed, according to the list of languages  here:
https://github.com/papoteur-mga/elograf/blob/f1cc17a9310bef311ff1cd1b83bc48a6538c3b39/elograf.pro#L32

**Comment by albanobattistella** [comment]
> Hello, Thanks for providing the translation. From which installation the translation is missing ? Translations are provided by a qm file which is computed when the setup is executed, according to the list of languages here:
> 
> https://github.com/papoteur-mga/elograf/blob/f1cc17a9310bef311ff1cd1b83bc48a6538c3b39/elograf.pro#L32

Hi,
the interface is not translated in italian.
We see all the translation but, is not translated in italian and remain on english by default.

**Comment by papoteur-mga** [comment]
Hi,
I don't know how you installed it on which system. Thus I can't be of any help.
Where do you see the translation if the interface is still in English?

**Comment by papoteur-mga** [comment]
No answer, thus closing.
