### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by OliverGronowski** [papoteur-mga/elograf#3]
I just installed elograf without sudo keyword in my Ubuntu via the terminal and after that installed nerd-dictatuon. However, after I installed nerd-dictatuon while having the elograf launched and sitting in the system tray bar, the icon won't go away when clicking exit, and also the configuration option does nothing when clicked. I then clicked elograf again in my App Menu Screen, but this just opened a duplicate icon in the system tray bar! Now I have two sitting there and do not know how to get rid of them. What am I doing wrong? Should I reinstall the both the nerd-dictatuon and elograf instances? If yes, how though(I am new to Linux)? Thank you very much for this app and any help incoming!

**Comment by papoteur-mga** [comment]
Hello,
You don't say anything about the model you should install.

> Models are expected to be installed in /usr/share/vosk-model/

**Comment by papoteur-mga** [comment]
The last release should fix the closing.
