### ISSUE TITLE
How do I pass options to nerd-dictation when using elograf?

### ISSUE THREAD

**Issue by cmt29** [papoteur-mga/elograf#4]
What is the best way to pass options to nerd-dictation (e.g. --full-sentences) when using elograf?

**Comment by papoteur-mga** [comment]
Hello,
From the icon, right clic - Configuration - Advanced
Some of the options are already provided, like "full sentence" as tick box.
For other not provided, you can add them as free text in the last line.

**Comment by papoteur-mga** [comment]
I have completed the README with reference to advanced dialogue.
