### ISSUE TITLE
elograf crashes when trying to access advanced config

### ISSUE THREAD

**Issue by cmt29** [papoteur-mga/elograf#5]
When I try and access advanced config elograf crashes. If run from console, then get the following output:

```
user@domain:~> elograf
QLayout: Attempting to add QLayout "" to ConfigPopup "", which already has a layout
QLayout: Attempting to add QLayout "" to ConfigPopup "", which already has a layout
Traceback (most recent call last):
  File "/home/user/bin/elograf-master/eloGraf/elograf.py", line 320, in advanced
    p = run(["pactl", "list", "sources"], capture_output=True, text=True, env=chenv)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
Aborted (core dumped)
user@domain:~>
```

**Comment by papoteur-mga** [comment]
The problem is that you use an old `Python` release. You need at least `3.7`.
> **Changed in version 3.7**: Added the text parameter, as a more understandable alias of universal_newlines. **Added the capture_output parameter.**
`pylupdate5` command are for generation translation files. If you don't need French, this is not a problem for you, except if the installation process is stuck because of.

**Comment by papoteur-mga** [comment]
Which Suse release do you use ?
You can create and use a virtualenv. This is mean for cases where Python release and modules from the system don't match your needs.

**Comment by cmt29** [comment]
I have OpenSuse Leap 15.3.

**Comment by papoteur-mga** [comment]
You can apply this patch against elograf.py which uses old form of system call.
[python3.6.patch.txt](https://github.com/papoteur-mga/elograf/files/8246634/python3.6.patch.txt)

**Comment by cmt29** [comment]
Thank you so much - that works perfectly. :clap:
