### ISSUE TITLE
Icon in XFCE

### ISSUE THREAD

**Issue by gitalm** [papoteur-mga/elograf#6]
Dear @papoteur-mga , thanks for elogtraf.

I installed it by using a symbolic link in /usr/bin to nerd-dictation. But in XFCE i just can change settings, but it is not changing the recording state

Thanks for the help
![image](https://user-images.githubusercontent.com/7422149/160083004-2169ef9a-8068-4799-94ad-0a4899f2a791.png)

**Comment by papoteur-mga** [comment]
Hello,
The program checks the state of the launched nerd-dictation process. Thus, if the icon is still striked, then it is because the process stops directly.
You can exit, then open a terminal and launch elograf. You could get some information about what happens.

**Comment by papoteur-mga** [comment]
Without more information, I close this issue report.
