### ISSUE TITLE
Crash if /usr/share/vosk-model doesn't exist.

### ISSUE THREAD

**Issue by jeanlofr** [papoteur-mga/elograf#7]
Hello, 
everything is in the title.
Distro: arch, everything up to date.
Crash if /usr/share/vosk-model doesn't exist. This happens if no custom model is set (first time launch of elograf).
Works fine if the directory is empty, just choose a custom model etc.

**Comment by papoteur-mga** [comment]
Thanks for the report.
It should be fixed now.
