### ISSUE TITLE
Failed to create a model

### ISSUE THREAD

**Issue by auwsom** [papoteur-mga/elograf#8]
Hi, this app looks really great to be able to control nerd-dictation.

Unfortunately, I got this error "FileNotFoundError: [Errno 2] No such file or directory: 'nerd-dictation'".

Does it need to be in the same directory? I have ND in ~/git/nerd-dictation. So I put that dir in my PATH, but it didnt resolve the error.

**Comment by auwsom** [comment]
So, I found my .profile isnt setting PATH args, but my .bashrc is.
I got past that error, but now have: 
```
Exception: Failed to create a model
write() failed: Broken pipe
```

**Comment by auwsom** [comment]
Okay, I just had to point the configuration custom model to:
/home/user/git/nerd-dictation/modelhuh

**Comment by papoteur-mga** [comment]
Hello,
I know that the installation can be tricky. This is the work of distributions to have all parts pulled in the same time.
I think also to a mechanism to choose and download directly a model.

**Comment by papoteur-mga** [comment]
Hello,
I just added a new release which allows the selection of the model and to download them from alphacei/vosk website.
You have to configure again the model.
For already imported model, give it a name.
